### ISSUE TITLE
add a reverse() Method to change the path

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/prototypo.js#2]
Sometimes we can't change the path direction manually (nodes dependencies). We may need a reverse() Method to avoid this kind of problem:

![reversepath](https://cloud.githubusercontent.com/assets/859119/6707370/b06daeb4-cd66-11e4-887a-ae03068a17b4.jpg)

**Comment by louisremi** [comment]
Won't fix, we'll find another way to work around that problem. For now let's just reverse the source
